name: BuildPR
on:
    pull_request:
        branches:
            - main
jobs:
    buildTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/prepare
            - run: yarn
            - run: yarn test
            - run: yarn build
